config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  root 'url_shorteners#new'
  resources :url_shorteners
  get "/:short_url", to: "url_shorteners#redirect", as: :short

  namespace :api do
    namespace :v1 do
      resources :url_shorteners, only: [:show, :index, :create, :update, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/url_shortener.rb
class UrlShortener < ApplicationRecord
    validates :original, presence: true, format: { with: URI::regexp(%w[http https]) }
    validates :short, uniqueness: true

    before_create :generate_short_url

    private

    def generate_short_url
        self.short = SecureRandom.alphanumeric(6)
    end
end

app/controllers/api/v1/url_shorteners_controller.rb
class Api::V1::UrlShortenersController < ApplicationController 
    before_action :authenticate_request, only: [:index, :show, :create, :update, :destroy]
    skip_before_action :verify_authenticity_token, only: [:create, :update, :destroy]

    def index
      page_size = params[:page_size] || 50
      page = params[:page] || 1
      @url_shorteners = UrlShortener.all.page(page).per(page_size)
      respond_to do |format|
        format.json { render json: @url_shorteners }  # Explicitly render JSON
      end
    end

    def create
      @url_shortener = UrlShortener.new(original: params[:original])
      if @url_shortener.save
        @url_shortener.update(short: @url_shortener.short)
        puts @url_shortener.inspect
        render json: { short_url: "#{request.base_url}/#{@url_shortener.short}" }, status: :created
      else
        render json: {
          success: false,
          message: "something went wrong.",
          errors: @url_shortener.errors.full_messages
        }
      end
    end

    def update
      @url_shortener = UrlShortener.find_by(id: params[:id])
      if @url_shortener.nil?
        render json: { success: false, message: 'URL Shortener not found' }, status: :not_found
        return
      end
      @url_shortener.short = SecureRandom.alphanumeric(6)
      if @url_shortener.update(original: params[:original], short: @url_shortener.short)
        render json: {"#{request.base_url}/#{@url_shortener.short}" }, status: :ok
      else
        render json: {
          success: false,
          message: "something went wrong.",
          errors: @url_shortener.errors.full_messages
        }
      end
    end


    def destroy
      @url_shortener = UrlShortener.find_by(id: params[:id])
      if @url_shortener.nil?
        render json: { success: false, message: 'URL Shortener not found' }, status: :not_found
      elsif @url_shortener.destroy
        render json: { success: true, message: 'URL Shortener successfully deleted' }, status: :ok
      else
        render json: { success: false, message: 'Failed to delete URL Shortener', errors: @url_shortener.errors.full_messages }, status: :unprocessable_entity
      end
    end

    def show
      @url_shortener = UrlShortener.find_by(id: params[:id])
      if @url_shortener
        render json: { 
          id: @url_shortener.id,
          original_url: @url_shortener.original,
          short_url: @url_shortener.short
        }, status: :ok
      else
        render json: { success: false, message: "URL Shortener not found" }, status: :not_found
      end
    end

    private

    def authenticate_request
      token = request.headers["Authorization"]
      puts "Authorization Header: #{token}"
      if token.present?
        secret_token = Rails.application.credentials.auth[:secret_token]
        render json: { error: "Unauthorized" }, status: :unauthorized if token != secret_token
      else
        render json: { error: "Unauthorized: Missing Authorization header" }
      end
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/url_shorteners_controller.rb
class UrlShortenersController < ApplicationController
  before_action :set_url_shortener, only: [:show, :edit, :update, :destroy]

  # GET /url_shorteners or /url_shorteners.json
  def index
    @url_shorteners = UrlShortener.page(params[:page]).per(50)
  end

  # GET /url_shorteners/1 or /url_shorteners/1.json
  def show
  end

  # GET /url_shorteners/new
  def new
    @url_shortener = UrlShortener.new
  end

  # GET /url_shorteners/1/edit
  def edit
  end


  def create
    @url_shortener = UrlShortener.find_or_create_by(url_shortener_params)
    if @url_shortener.persisted?
      @url_shortener.update(short: @url_shortener.short)
      flash[:notice] = "Shortened URL: #{request.base_url}/#{@url_shortener.short}"
      redirect_to url_shortener_url(@url_shortener)
    else
      flash[:alert] = @url.errors.full_messages.to_sentence
      render :new
    end
  end

  # PATCH/PUT /url_shorteners/1 or /url_shorteners/1.json
  def update
    respond_to do |format|
      @url_shortener.short = SecureRandom.alphanumeric(6)
      if @url_shortener.update(original: params[:url_shortener][:original], short: @url_shortener.short)
        format.html { redirect_to @url_shortener, notice: "Url shortener was successfully updated." }
        format.json { render :show, status: :ok, location: @url_shortener }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @url_shortener.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /url_shorteners/1 or /url_shorteners/1.json
  def destroy
    @url_shortener.destroy!

    respond_to do |format|
      format.html { redirect_to url_shorteners_path, status: :see_other, notice: "Url shortener was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def redirect
    url_shortener = UrlShortener.find_by(short: params[:short_url])
    if url_shortener
      redirect_to url_shortener.original, allow_other_host: true
    else
      render plain: "URL not found", status: :not_found
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url_shortener
      @url_shortener = UrlShortener.find_by(id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def url_shortener_params
      params.expect(url_shortener: [ :original, :short ])
    end

    def short_url(short_code)
      request.base_url + "/" + short_code
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_shorteners_helper.rb
module UrlShortenersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Url Shorterns App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= yield :head %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/url_shorteners/_form.html.erb
<%= form_with model:@url_shortener,local: true do |form| %>
  <% if @url_shortener.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@url_shortener.errors.count, "error") %> prohibited this url_shortener from being saved:</h2>

      <ul>
        <% @url_shortener.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :original, style: "display: block" %>
    <%= form.text_field :original %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/url_shorteners/edit.html.erb
<% content_for :title, "Editing url shortener" %>

<h3>Editing url shortener</h3>

<%= render "form", url_shortener: @url_shortener %>

<br>

<div>
  <%= link_to "Show this url shortener", @url_shortener %> |
  <%= link_to "Back to url shorteners", url_shorteners_path %>
</div>

app/views/url_shorteners/index.html.erb
<p style="color: green"><%= notice %></p>

<h2>URL Shorterns </h2>

<div class="text-right p-2">
  <%= link_to '+ New url shortene', new_url_shortener_path,
    class: "btn btn-outline-primary" %>
</div>

<div class="row">
  <div class="container-fluid mt-3">
    <div class="table-responsive-sm bg-white shadow-bottom">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Sl. No.</th>
            <th>Original URL</th>
            <th>Short URL</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% page = @url_shorteners.current_page %>
          <% @url_shorteners.each_with_index do |url, index| %>
            <tr>
              <td><%= (((page == 0 ? 1 : page) - 1) * 10) + (index + 1) %></td>
              <td><%= url.original %></td>
              <td><%= url.short %></td>
              <td>
                <div class="btn-stack">
                  <%= link_to 'Details', url, remote: true,
                    class: "btn btn-sm btn-outline-info" %>
                </div>
              </td>
            </tr>
          <% end %>
          <% if @url_shorteners.blank? %>
            <tr>
              <td colspan="5"><center><h4>No records found for you!</h4></center></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/url_shorteners/new.html.erb
<% content_for :title, "New url shortener" %>

<h3>New url shortener</h3>

<%= render "form", url_shortener: @url_shortener %>

<br>

<div>
  <%= link_to "Back to url shorteners", url_shorteners_path %>
</div>

app/views/url_shorteners/show.html.erb
<p style="color: green"><%= notice %></p>
<div>
  <p>
    <strong>Original:</strong>
    <%= @url_shortener.original %>
  </p>

  <p>
    <strong>Short:</strong>
    <%= request.base_url+"/"+@url_shortener.short %>
  </p>

</div>

<div>
  <%= link_to "Edit this url shortener", edit_url_shortener_path(@url_shortener) %> |
  <%= link_to "Back to url shorteners", url_shorteners_path %>

  <%= button_to "Destroy this url shortener", @url_shortener, method: :delete %>
</div>